"""add is_admin to users

Revision ID: 2d862cdabbb6
Revises: e, 3, e, f, 7, 6, f, b, 9, e, 6, a
Create Date: 2025-07-23 17:03:00.407899

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d862cdabbb6'
down_revision = 'e3ef76fb9e6a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ### 