"""Extend candidate_profiles to store raw file and metadata

Revision ID: 3f74791f842f
Revises: d, 7, 2, 4, d, 3, b, 2, 7, 2, c, f
Create Date: 2025-08-09 13:32:54.029537

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f74791f842f'
down_revision = 'd724d3b272cf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('resume_file', sa.LargeBinary(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('candidate_profiles', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'file_size')
    op.drop_column('candidate_profiles', 'content_type')
    op.drop_column('candidate_profiles', 'file_name')
    op.drop_column('candidate_profiles', 'resume_file')
    # ### end Alembic commands ### 