"""Add completed_at and completed_ip to interviews

Revision ID: 779d02bbe3af
Revises: 3, f, 7, 4, 7, 9, 1, f, 8, 4, 2, f
Create Date: 2025-08-15 00:15:36.214344

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779d02bbe3af'
down_revision = '3f74791f842f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('completed_ip', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'completed_ip')
    op.drop_column('interviews', 'completed_at')
    # ### end Alembic commands ### 