"""add token fields to candidates

Revision ID: b998b75d472d
Revises: e, 6, 5, 3, d, e, c, e, 5, 4, 6, 4
Create Date: 2025-07-23 18:44:03.293446

"""
from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b998b75d472d'
down_revision = 'e653dece5464'
branch_labels = None
depends_on = None

def upgrade():
    # 1. sütunu nullable ekle
    op.add_column('candidates', sa.Column('token', sa.String(length=64), nullable=True))
    op.add_column('candidates', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('status', sa.String(length=20), server_default="pending", nullable=False))

    # 2. eski satırları doldur
    from uuid import uuid4
    import datetime as dt
    op.execute(text("""
        UPDATE candidates
        SET token = substring(md5(random()::text) for 32),
            expires_at = NOW() + interval '365 days',
            status = 'pending'
        WHERE token IS NULL;
    """))

    # 3. null constraint koy
    op.alter_column('candidates', 'token', nullable=False)
    op.alter_column('candidates', 'expires_at', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_column('candidates', 'used_at')
    op.drop_column('candidates', 'expires_at')
    op.drop_column('candidates', 'token')
    op.drop_column('candidates', 'status')
    # ### end Alembic commands ### 