"""add media urls to interview

Revision ID: cd5e45a4aeb3
Revises: b, 9, 9, 8, b, 7, 5, d, 4, 7, 2, d
Create Date: 2025-07-25 18:30:14.706255

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5e45a4aeb3'
down_revision = 'b998b75d472d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidates', ['token'])
    op.add_column('interviews', sa.Column('audio_url', sa.String(length=512), nullable=True))
    op.add_column('interviews', sa.Column('video_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'video_url')
    op.drop_column('interviews', 'audio_url')
    op.drop_constraint(None, 'candidates', type_='unique')
    # ### end Alembic commands ### 