"""add is_admin default false

Revision ID: e653dece5464
Revises: 2, d, 8, 6, 2, c, d, a, b, b, b, 6
Create Date: 2025-07-23 17:07:45.451298

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e653dece5464'
down_revision = '2d862cdabbb6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 